import { Ad1, Ad2, Ad4 } from "@/components/ads/ads";

const link = "/vidyadhan-scholarship-2024";

const cPage = () => {
  const page = `
 <article id="post-194874" class="single-view post-194874 post type-post status-publish format-standard has-post-thumbnail hentry category-scholarship category-sarkari-yojana" itemprop="blogPost" itemscope="" itemtype="http://schema.org/BlogPosting" style="height: auto !important;">

		<h2 class="entry-title" itemprop="headline"><a href="https://biharhelp.in/mukhyamantri-meghavriti-yojana-2024/"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Mukhyamantri Meghavriti Yojana 2024 Online Apply – Chief Minister Meghavriti Yojana 2024, 12th pass will get Rs 15,000</font></font></a></h2>
<div class="entry-content cf" itemprop="text" style="height: auto !important;">
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Mukhyamantri Medhavriti Yojana 2024: There is </font></font></strong><font style="vertical-align: inherit;"><strong><font style="vertical-align: inherit;">good news&nbsp;</font></strong><font style="vertical-align: inherit;"> for&nbsp; </font><font style="vertical-align: inherit;">all those&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Scheduled Caste / Tribe i.e. SC &amp; ST&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> students of Bihar state who </font><font style="vertical-align: inherit;">have secured&nbsp; </font><strong><font style="vertical-align: inherit;">&nbsp;first and second division in </font></strong><strong><font style="vertical-align: inherit;">Inter because the list of all such students has been prepared by </font></strong><strong><font style="vertical-align: inherit;">the Bihar Education Board,&nbsp;</font></strong><font style="vertical-align: inherit;"> under which a total of&nbsp; </font><strong><font style="vertical-align: inherit;">2 lakh </font></strong><strong><span style="color: #000000;"><font style="vertical-align: inherit;">students</font></span></strong><strong><font style="vertical-align: inherit;"> will get scholarship.</font></strong></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font><span style="color: #000000;"><font style="vertical-align: inherit;"></font></span><font style="vertical-align: inherit;"></font></strong></p>
<h2 style="text-align: center;"><span class="ez-toc-section" id="%E0%A4%B8%E0%A4%BE%E0%A4%B2_2024_%E0%A4%AE%E0%A5%87_%E0%A4%95%E0%A4%B0%E0%A4%A8%E0%A5%87_%E0%A4%B5%E0%A4%BE%E0%A4%B2%E0%A5%87_%E0%A4%B8%E0%A5%8D%E0%A4%9F%E0%A5%82%E0%A4%A1%E0%A5%87%E0%A4%82%E0%A4%9F%E0%A5%8D%E0%A4%B8_%E0%A4%B9%E0%A5%87%E0%A4%A4%E0%A5%81_%E2%82%B9_15000_%E0%A4%B0%E0%A5%81%E0%A4%AA%E0%A4%AF%E0%A5%8B_%E0%A4%95%E0%A5%80_%E0%A4%B8%E0%A5%8D%E0%A4%95%E0%A5%89%E0%A4%B2%E0%A4%B0%E0%A4%B6%E0%A4%BF%E0%A4%AA_%E0%A4%B9%E0%A5%87%E0%A4%A4%E0%A5%81_%E0%A4%86%E0%A4%B5%E0%A5%87%E0%A4%A6%E0%A4%A8_%E0%A4%B6%E0%A5%81%E0%A4%B0%E0%A5%81_%E2%80%93_Mukhyamantri_MeghaVriti_Yojana_2024" ez-toc-data-id="#साल_2024_मे_करने_वाले_स्टूडेंट्स_हेतु_₹_15000_रुपयो_की_स्कॉलरशिप_हेतु_आवेदन_शुरु_–_Mukhyamantri_MeghaVriti_Yojana_2024"></span><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Application started for scholarship of ₹ 15,000 for students doing their graduation in the year 2024 – Mukhyamantri MeghaVriti Yojana 2024</font></font></strong><span class="ez-toc-section-end"></span></h2>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">There is big news for&nbsp; </font><font style="vertical-align: inherit;">all our students who&nbsp; have </font><strong><font style="vertical-align: inherit;">applied&nbsp;</font></strong><font style="vertical-align: inherit;"> for&nbsp; </font><strong><font style="vertical-align: inherit;">scholarship&nbsp;</font></strong><font style="vertical-align: inherit;"> in&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">the year 2024&nbsp; , that </font></font></strong><font style="vertical-align: inherit;"><strong><font style="vertical-align: inherit;">the application process&nbsp;</font></strong><font style="vertical-align: inherit;"> has been started&nbsp; </font><font style="vertical-align: inherit;">by&nbsp; </font><strong><font style="vertical-align: inherit;">the Government of Bihar&nbsp;</font></strong><font style="vertical-align: inherit;"> for&nbsp; </font><strong><font style="vertical-align: inherit;">matriculation pass students&nbsp;</font></strong><font style="vertical-align: inherit;"> under the&nbsp; </font><strong><font style="vertical-align: inherit;">"Mukhyamantri MeghaVriti Yojana",&nbsp; in which on applying, you will get the benefit of </font></strong><strong><font style="vertical-align: inherit;">a scholarship&nbsp;</font></strong><font style="vertical-align: inherit;"> of&nbsp; </font><strong><font style="vertical-align: inherit;">full ₹ 10,000&nbsp;</font></strong><font style="vertical-align: inherit;"> and that is why we will tell you in detail&nbsp; about </font><strong><font style="vertical-align: inherit;">Mukhyamantri MeghaVriti Yojana 2024&nbsp;</font></strong><font style="vertical-align: inherit;"> in this article , to get complete detailed information of which you have to stay with us.</font></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Here we want to tell you that&nbsp; </font><font style="vertical-align: inherit;">to&nbsp; </font><strong><font style="vertical-align: inherit;">apply&nbsp;</font></strong><font style="vertical-align: inherit;"> for&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Mukhyamantri MeghaVriti Yojana 2024,&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> you have to apply by following&nbsp; </font><strong><font style="vertical-align: inherit;">the&nbsp; </font></strong><strong><font style="vertical-align: inherit;">online application process&nbsp;</font></strong><font style="vertical-align: inherit;"> ,&nbsp; in which you do not have any problem, for this we will tell you about </font><strong><font style="vertical-align: inherit;">the entire application process&nbsp;</font></strong><font style="vertical-align: inherit;"> so that you can&nbsp; </font><strong><font style="vertical-align: inherit;">apply&nbsp;</font></strong><font style="vertical-align: inherit;"> without any problem and&nbsp; </font><font style="vertical-align: inherit;">get the benefit of </font><strong><font style="vertical-align: inherit;">scholarship&nbsp; and</font></strong></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font></p>
<h2 style="text-align: center;"><span class="ez-toc-section" id="Mukhyamantri_MeghaVriti_Yojana_2024_%E2%80%93_%E0%A4%86%E0%A4%B5%E0%A5%87%E0%A4%A6%E0%A4%A8_%E0%A4%B8%E0%A5%87_%E0%A4%AA%E0%A4%B9%E0%A4%B2%E0%A5%87%E0%A4%82_%E0%A4%A7%E0%A5%8D%E0%A4%AF%E0%A4%BE%E0%A4%A8_%E0%A4%B0%E0%A4%96%E0%A4%A8%E0%A5%87_%E0%A4%B5%E0%A4%BE%E0%A4%B2%E0%A5%80_%E0%A4%AC%E0%A4%BE%E0%A4%A4%E0%A5%87%E0%A4%82" ez-toc-data-id="#Mukhyamantri_MeghaVriti_Yojana_2024_–_आवेदन_से_पहलें_ध्यान_रखने_वाली_बातें"></span><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Mukhyamantri MeghaVriti Yojana 2024 – Things to keep in mind before applying&nbsp;</font></font></strong><span class="ez-toc-section-end"></span></h2>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">To apply for Mukhyamantri Meghavriti Yojana 2024,&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> some things have to be kept in mind –</font></font></p>
<ul style="list-style:disc;">
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Matric 2024 Scholarship Portal is going to open soon for girl students only,</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Student must have Registration Number, Student Name, Father Name, Mother Name, District Name, Total Marks, Roll Number, Date of Birth (as per 10th), Aadhar Details, Gender, Category, Mobile Number, Alternate Mobile Number and Email ID for Registration.</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">This portal is currently open only for INTERSCST (12th) pass from BSEB 2024,</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">As per the advertisement of INTERSCST 2024 scholarship of Education Department, Government of Bihar, eligible girl students need to apply,</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">A student will be eligible for this scholarship only once.</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">The name in Aadhaar should be same as that of the student (as per the applicant),</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">A unique mobile no. of the student or family member can be used for registration, activate it for further alert,</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">A unique email ID of the student or family member can be used for registration, activate it for further alert,</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">One can register on the portal by providing details like </font><font style="vertical-align: inherit;">student name, father’s name, total marks obtained </font></font><span style="color: #000000;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">, </font></font><a style="color: #000000;" href="https://biharhelp.in/neet-pg-exam-date-2024/"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">date of birth as per 10th</font></font></a><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> , Aadhaar details, mobile number and email etc.</font></font></span><font style="vertical-align: inherit;"></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">After registration, bank account verification will be done. After bank verification, user ID and password will be sent to mobile. Wait till then and do not panic. If you do not get user ID and password within 15 days then click on Get User ID and Password, Check your status or SMS (BRGOVT),</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Do not share your User ID and Password with anyone else. If a student's User ID and Password are not sent within 15 days, do not panic, they will be sent as soon as the verification is done.</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Make sure that the submission and finalization of the application is being done in your presence. You will be solely responsible for any error or mischief committed by the cyber and</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">After final completion of the form, submit the application form on the portal and print a copy of the application form for future reference. No changes are allowed after final submission of the form etc.</font></font></li>
</ul>
<p><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">You have to apply&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> keeping in mind&nbsp; </font><strong><font style="vertical-align: inherit;">all the above points&nbsp;</font></strong><font style="vertical-align: inherit;"> so that you can apply easily and&nbsp; </font><font style="vertical-align: inherit;">apply for </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">the scholarship&nbsp; .</font></font></strong><font style="vertical-align: inherit;"></font></p>
<h2 style="text-align: center;"><span class="ez-toc-section" id="Required_Documents_For_Mukhyamantri_Meghavriti_Yojana_2024" ez-toc-data-id="#Required_Documents_For_Mukhyamantri_Meghavriti_Yojana_2024"></span><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Required Documents For Mukhyamantri Meghavriti Yojana 2024?</font></font></strong><span class="ez-toc-section-end"></span></h2>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">To apply for this scholarship, you&nbsp; will have to </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">submit some documents&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> which are as follows –</font></font></p>
<ul style="list-style:disc;">
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Aadhaar card of student,</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Bank Account Passbook,</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Income Certificate,</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Address proof,</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">caste certificate,</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Active mobile number and</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Passport size photograph etc.</font></font></li>
</ul>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">By filling all the above documents, you can easily&nbsp; apply for </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">this scholarship&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> and avail its benefits.</font></font></p>

<h2 style="text-align: center;"><span class="ez-toc-section" id="%E0%A4%AE%E0%A5%81%E0%A4%96%E0%A5%8D%E0%A4%AF%E0%A4%AE%E0%A4%82%E0%A4%A4%E0%A5%8D%E0%A4%B0%E0%A5%80_%E0%A4%AE%E0%A5%87%E0%A4%98%E0%A4%BE%E0%A4%B5%E0%A5%83%E0%A4%A4%E0%A5%8D%E0%A4%A4%E0%A4%BF_%E0%A4%AF%E0%A5%8B%E0%A4%9C%E0%A4%A8%E0%A4%BE_2024_%E2%80%93_%E0%A4%86%E0%A4%B5%E0%A5%87%E0%A4%A6%E0%A4%A8_%E0%A4%B9%E0%A5%87%E0%A4%A4%E0%A5%81_%E0%A4%95%E0%A5%8D%E0%A4%AF%E0%A4%BE_%E0%A4%AF%E0%A5%8B%E0%A4%97%E0%A5%8D%E0%A4%AF%E0%A4%A4%E0%A4%BE_%E0%A4%9A%E0%A4%BE%E0%A4%B9%E0%A4%BF%E0%A4%8F" ez-toc-data-id="#मुख्यमंत्री_मेघावृत्ति_योजना_2024_–_आवेदन_हेतु_क्या_योग्यता_चाहिए"></span><span style="color: #000000;"><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Chief Minister Meghavriti Yojana 2024 – What is the eligibility required for application?</font></font></strong></span><span class="ez-toc-section-end"></span></h2>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">All the students who want to apply for this scholarship must fulfill certain eligibility criteria which are as follows –</font></font></p>
<ul style="list-style:disc;">
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">The applicant&nbsp; </font><font style="vertical-align: inherit;">must have passed </font><strong><font style="vertical-align: inherit;">Intermediate&nbsp;</font></strong><font style="vertical-align: inherit;"> in&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">the year 2024&nbsp; ,</font></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Applicant student </font><font style="vertical-align: inherit;">should be from </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">SC / ST category&nbsp; and</font></font></strong><font style="vertical-align: inherit;"></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">The student&nbsp; </font><font style="vertical-align: inherit;">should be a native of </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Bihar state&nbsp; etc.</font></font></strong><font style="vertical-align: inherit;"></font></li>
</ul>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">By fulfilling the above eligibility criteria, you can easily&nbsp; </font><strong><font style="vertical-align: inherit;">apply&nbsp;</font></strong><font style="vertical-align: inherit;"> for&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">scholarship&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> and avail its benefits.</font></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font></p>
<h2 style="text-align: center;"><span class="ez-toc-section" id="How_to_Apply_Online_In_Mukhyamantri_Meghavriti_Yojana_2024" ez-toc-data-id="#How_to_Apply_Online_In_Mukhyamantri_Meghavriti_Yojana_2024"></span><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">How to Apply Online in Mukhyamantri Meghavriti Yojana 2024?</font></font></strong><span class="ez-toc-section-end"></span></h2>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">All our students who&nbsp; want to apply for </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">the scholarship scheme&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> will have to follow some steps which are as follows –</font></font></p>
<ul style="list-style:disc;">
<li>
<p style="text-align: left;"><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">To apply&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> for&nbsp; </font><strong><font style="vertical-align: inherit;">Mukhyamantri Meghavriti Yojana 2024,&nbsp;</font></strong><font style="vertical-align: inherit;"> first of all you&nbsp; </font><font style="vertical-align: inherit;">have to come to the home page of its </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">official website&nbsp;&nbsp; ,</font></font></strong><font style="vertical-align: inherit;"></font></p>
</li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">After coming to the home page, you&nbsp; will get the option of </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Apply Now&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> on which you will have to click, after which&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">the Application Form&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> will open in front of you, which you will have to fill carefully,</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">The required documents&nbsp; need to </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">be scanned&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> and uploaded</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">In the last step, you&nbsp; </font><font style="vertical-align: inherit;">will have to click on the submit option after which you&nbsp; </font><font style="vertical-align: inherit;">will&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">get&nbsp; </font></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">the&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> application&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">receipt&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> which you will have to </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">print&nbsp; .</font></font></strong><font style="vertical-align: inherit;"></font></li>
</ul>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Finally, this way all our students can apply online for this scholarship and avail the benefits.</font></font></p>
<h2><span class="ez-toc-section" id="%E0%A4%B8%E0%A4%BE%E0%A4%B0%E0%A4%BE%E0%A4%82%E0%A4%B6" ez-toc-data-id="#सारांश"></span><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Summary</font></font></strong><span class="ez-toc-section-end"></span></h2>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">In this article, we </font><font style="vertical-align: inherit;">have told&nbsp; you in detail not </font></font><span style="color: #000000;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">only </font><font style="vertical-align: inherit;">about </font></font><strong><a style="color: #000000;" href="https://biharhelp.in/neet-pg-2024/"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Mukhyamantri Meghavriti Yojana 2024</font></font></a>&nbsp;</strong><font style="vertical-align: inherit;"></font></span><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> but we have also told you about&nbsp; </font><strong><font style="vertical-align: inherit;">applying&nbsp;</font></strong><font style="vertical-align: inherit;"> in&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Mukhyamantri Meghavriti Yojana 2024&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> so that you can&nbsp; easily </font><strong><font style="vertical-align: inherit;">apply&nbsp;</font></strong><font style="vertical-align: inherit;"> for&nbsp; </font><strong><font style="vertical-align: inherit;">scholarship&nbsp; and apply for </font></strong><strong><font style="vertical-align: inherit;">scholarship&nbsp;</font></strong><font style="vertical-align: inherit;"> and get its benefits and</font></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Finally, at the end of the article, we hope that you liked our article very much, for which you will like, share and comment on our article.</font></font></p>

</article>
  `;

  return (
    <section className="w-full mx-auto max-w-[420px] flex flex-col rounded-2xl p-2 border-2 border-gray-700 demo">
      <div className="border-y-2 border-gray-700">
        <Ad4 />
      </div>
      <div className="w-full my-4 flex items-center justify-center">
        <iframe
          id="twitter-widget-0"
          allowTransparency={true}
          allowFullScreen={true}
          title="X Post"
          style={{
            position: "static",
            visibility: "visible",
            width: "320px",
            height: "298px",
            display: "block",
          }}
          src="https://platform.twitter.com/embed/Tweet.html?dnt=false&amp;embedId=twitter-widget-0&amp;features=eyJ0ZndfdGltZWxpbmVfbGlzdCI6eyJidWNrZXQiOltdLCJ2ZXJzaW9uIjpudWxsfSwidGZ3X2ZvbGxvd2VyX2NvdW50X3N1bnNldCI6eyJidWNrZXQiOnRydWUsInZlcnNpb24iOm51bGx9LCJ0ZndfdHdlZXRfZWRpdF9iYWNrZW5kIjp7ImJ1Y2tldCI6Im9uIiwidmVyc2lvbiI6bnVsbH0sInRmd19yZWZzcmNfc2Vzc2lvbiI6eyJidWNrZXQiOiJvbiIsInZlcnNpb24iOm51bGx9LCJ0ZndfZm9zbnJfc29mdF9pbnRlcnZlbnRpb25zX2VuYWJsZWQiOnsiYnVja2V0Ijoib24iLCJ2ZXJzaW9uIjpudWxsfSwidGZ3X21peGVkX21lZGlhXzE1ODk3Ijp7ImJ1Y2tldCI6InRyZWF0bWVudCIsInZlcnNpb24iOm51bGx9LCJ0ZndfZXhwZXJpbWVudHNfY29va2llX2V4cGlyYXRpb24iOnsiYnVja2V0IjoxMjA5NjAwLCJ2ZXJzaW9uIjpudWxsfSwidGZ3X3Nob3dfYmlyZHdhdGNoX3Bpdm90c19lbmFibGVkIjp7ImJ1Y2tldCI6Im9uIiwidmVyc2lvbiI6bnVsbH0sInRmd19kdXBsaWNhdGVfc2NyaWJlc190b19zZXR0aW5ncyI6eyJidWNrZXQiOiJvbiIsInZlcnNpb24iOm51bGx9LCJ0ZndfdXNlX3Byb2ZpbGVfaW1hZ2Vfc2hhcGVfZW5hYmxlZCI6eyJidWNrZXQiOiJvbiIsInZlcnNpb24iOm51bGx9LCJ0ZndfdmlkZW9faGxzX2R5bmFtaWNfbWFuaWZlc3RzXzE1MDgyIjp7ImJ1Y2tldCI6InRydWVfYml0cmF0ZSIsInZlcnNpb24iOm51bGx9LCJ0ZndfbGVnYWN5X3RpbWVsaW5lX3N1bnNldCI6eyJidWNrZXQiOnRydWUsInZlcnNpb24iOm51bGx9LCJ0ZndfdHdlZXRfZWRpdF9mcm9udGVuZCI6eyJidWNrZXQiOiJvbiIsInZlcnNpb24iOm51bGx9fQ%3D%3D&amp;frame=false&amp;hideCard=false&amp;hideThread=false&amp;id=1743620721018826896&amp;lang=en&amp;maxWidth=560px&amp;origin=https%3A%2F%2Fbuzzlenews.com%2Fc.html&amp;sessionId=355e154fe49335923557d26b8a2bbd9f883e149b&amp;theme=light&amp;widgetsVersion=2615f7e52b7e0%3A1702314776716&amp;width=550px"
          data-tweet-id="1743620721018826896"
        ></iframe>
      </div>
      <div className="border-y-2 border-gray-700">
        <Ad2 />
      </div>

      <div dangerouslySetInnerHTML={{ __html: page }} className="demo"></div>
    </section>
  );
};

export default cPage;
