import { Ad2, SmallAd } from "@/components/ads/ads";
import ExtraButton from "@/components/etc/button-extra";

const link = "/driving-licence";

const aPage = () => {
  const page = `
  <article id="post-4940" class="post-4940 post type-post status-publish format-standard has-post-thumbnail hentry category-4 category-13 tag-l3 infinite-scroll-item no-featured-image-padding" itemtype="https://schema.org/CreativeWork" itemscope="" style="height: auto !important;">
<div class="inside-article" style="height: auto !important;">
<header class="entry-header">
<h1 class="entry-title" itemprop="headline"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">How to apply and check driving license online</font></font></h1> </header>
<div class="entry-content" itemprop="text" style="height: auto !important;">


<p><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">It is mandatory for us to get a driving license to drive any type of vehicle. If you drive a vehicle without a driving license, it is considered a violation of law. After completing 18 years of age, any person can get a license and with this he gets the right to drive a vehicle. License is also an important document which is also very useful as our identity card.&nbsp;</font></font></span></p>
<p><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">In the digital age, the Government of India has provided the facility of getting a driving license online. With this, you can apply for a driving license from home with the help of internet. Earlier, it used to take a lot of time to get a driving license. Because for this, we had to visit the RTO or get this work done by paying money to an agent, it cost both time and money.&nbsp;</font></font></span></p>
<p><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">But now you can do this process yourself sitting at home. In this article, we are giving you step by step information about how to apply for driving license online. But before that, let us know which documents you will need for this -</font></font></span></p>
<ul style="list-style:disc;text-align:left" >
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Aadhar card</font></font></span></li>
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Birth Certificate / 10th Marksheet / PAN Card</font></font></span></li>
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Passport size photo</font></font></span></li>
</ul>
<h2><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Step by step process</font></font></span></h2>
<ul style="list-style:disc;text-align:left" >
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">To apply for a driving license, first you have to visit the official website. Whose link is – </font></font></span><a href="https://parivahan.gov.in/parivahan/"><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">https://parivahan.gov.in/parivahan/</font></font></span></a><span style="font-weight: 400;">&nbsp;</span></li>
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">As soon as this website opens, you get to see many options here. You have to go to the option of </font></font></span><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Online Services among these </font></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">and a list will open in front of you from which you </font></font></span><font style="vertical-align: inherit;"><span style="font-weight: 400;"><font style="vertical-align: inherit;">have to click on the second option </font></span></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Driving License Related Service .</font></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"></font></span></li>
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">After this a new screen will open in front of you where you will be asked about your state. Here you select your state and click </font></font></span><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Continue </font></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">.</font></font></span></li>
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">After this, on the next screen you will see many options, here first of all you </font></font></span><font style="vertical-align: inherit;"><span style="font-weight: 400;"><font style="vertical-align: inherit;">have to click on the option </font></span></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Apply For Learners License .</font></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"></font></span></li>
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">On the next screen you </font></font></span><font style="vertical-align: inherit;"><span style="font-weight: 400;"><font style="vertical-align: inherit;">will be told about </font></span></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">the 7 steps that you have to follow while applying for the license online. You </font></font></b><font style="vertical-align: inherit;"><span style="font-weight: 400;"><font style="vertical-align: inherit;">have to proceed further by clicking on the </font></span><b><font style="vertical-align: inherit;">Continue button here.</font></b></font><span style="font-weight: 400;"><font style="vertical-align: inherit;"></font></span><b><font style="vertical-align: inherit;"></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"></font></span></li>
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">On the next screen you have to select your </font></font></span><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">category </font></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">, like </font></font></span><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">General, Ex Servicemen, Handicapped </font></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">etc. After this </font></font></span><font style="vertical-align: inherit;"><span style="font-weight: 400;"><font style="vertical-align: inherit;">click on </font></span></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">the SUBMIT button.</font></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"></font></span></li>
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">On the next screen you will get two options – </font></font></span><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Via Aadhar Authentication </font></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">and </font></font></span><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Without Aadhar Authentication </font></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">. If you choose the second option then you will have to visit the RTO after this. Since we are applying online here, we will choose the first option and proceed further.&nbsp;</font></font></span></li>
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">A small form will open on the next screen in which you will be asked for Aadhaar number. As soon as you enter the Aadhaar number, an OTP will be sent to the mobile number linked with your Aadhaar card. You have to enter the OTP and </font></font></span><font style="vertical-align: inherit;"><span style="font-weight: 400;"><font style="vertical-align: inherit;">click on </font></span></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">the Authenticate button.</font></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"></font></span></li>
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">On the next screen you will see a form, this form will be automatically filled because the portal takes all the details from your Aadhaar card. You </font></font></span><font style="vertical-align: inherit;"><span style="font-weight: 400;"><font style="vertical-align: inherit;">have to click on </font></span></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">the Proceed button here.</font></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"></font></span></li>
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"></font></span><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">A dialog box </font></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">will appear </font></font></span><font style="vertical-align: inherit;"><span style="font-weight: 400;"><font style="vertical-align: inherit;">on the next screen which you have to click </font></span></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">OK </font></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">. Here you will see a form in which you will enter the details asked.&nbsp;</font></font></span></li>
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Here you also have to select the type of your license. Like whether you want to get a license for a geared motorcycle or a car license or both or you want to get a license to drive any other heavy vehicle.&nbsp;</font></font></span></li>
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Here you will be given two more options, the first of which is whether your driving license has been cancelled before or not. If not, then leave it as it is, otherwise click on </font></font></span><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">YES </font></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">. If you have taken training from a driving school, then click on </font></font></span><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">YES </font></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">, otherwise leave it as it is.</font></font></span></li>
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">After this you </font></font></span><font style="vertical-align: inherit;"><span style="font-weight: 400;"><font style="vertical-align: inherit;">will see a </font></span></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">yellow box. This is the button of </font></font></b><font style="vertical-align: inherit;"><b><font style="vertical-align: inherit;">Self Declaration Form. </font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;">As soon as you click on it, a form will appear in front of you. In this, you will be asked about your fitness and health. You have to answer it in yes or no only. For this you </font></span><span style="font-weight: 400;"><font style="vertical-align: inherit;">can tick on </font></span><b><font style="vertical-align: inherit;">YES or NO and </font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;">can </font></span><b><font style="vertical-align: inherit;">SUBMIT .</font></b></font><span style="font-weight: 400;"><font style="vertical-align: inherit;"></font></span><b><font style="vertical-align: inherit;"></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"></font></span><b><font style="vertical-align: inherit;"></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"></font></span><b><font style="vertical-align: inherit;"></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"></font></span></li>
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">On submitting, you will be asked whether all the details are correct? Here you should check the details once because once you click on the OK button, you will not be able to change the details again. If everything is correct then click on </font></font></span><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">the OK </font></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">button and proceed further.</font></font></span></li>
<li><b><font style="vertical-align: inherit;"></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">As soon as you click on </font></font></span><font style="vertical-align: inherit;"><b><font style="vertical-align: inherit;">the OK button, your application has been successfully submitted. Here you will get an </font></b></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Application Number </font></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">, you have to write it down. And after this, </font></font></span><font style="vertical-align: inherit;"><span style="font-weight: 400;"><font style="vertical-align: inherit;">click on the </font></span></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Next button.</font></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"></font></span></li>
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">After this we have to upload our documents. In this we have to enter the Application Number and </font></font></span><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Date of Birth </font></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">and </font></font></span><font style="vertical-align: inherit;"><span style="font-weight: 400;"><font style="vertical-align: inherit;">click on </font></span></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">the SUBMIT button.</font></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"></font></span></li>
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"></font></span><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Now here you have to upload two documents, first is the Age Proof document </font></font></b><font style="vertical-align: inherit;"><span style="font-weight: 400;"><font style="vertical-align: inherit;">showing your date of birth and </font></span></font><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">second </font></font></span><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">is the Address Proof&nbsp;</font></font></b></li>
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">For age proof, you can upload a photo of your mark sheet, PAN card or Aadhar card. Keep in mind that the file type </font></font></span><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">should be JPEG or PDFG and it should not be more than 500 KB.&nbsp;</font></font></b></li>
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">You have to upload the Address Proof in the same way and </font></font></span><font style="vertical-align: inherit;"><span style="font-weight: 400;"><font style="vertical-align: inherit;">click on&nbsp; </font></span></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">the Confirm button.</font></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"></font></span></li>
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">In the next step you have to upload </font></font></span><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">photo and signature </font></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">. If you have uploaded Aadhar card then you do not need to upload photo. To upload signature, you have to take a photo of the signature and upload it. Now </font></font></span><font style="vertical-align: inherit;"><span style="font-weight: 400;"><font style="vertical-align: inherit;">click on </font></span></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Upload and View Files .</font></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"></font></span></li>
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Now you have to click on </font></font></span><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Save Photo Signature Image File </font></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">and then </font></font></span><font style="vertical-align: inherit;"><span style="font-weight: 400;"><font style="vertical-align: inherit;">click on&nbsp; </font></span></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Next .</font></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"></font></span></li>
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">In the next step you </font></font></span><font style="vertical-align: inherit;"><span style="font-weight: 400;"><font style="vertical-align: inherit;">have to process </font></span></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">the fee payment . </font></font></b><font style="vertical-align: inherit;"><span style="font-weight: 400;"><font style="vertical-align: inherit;">After clicking on </font></span><b><font style="vertical-align: inherit;">the Fee Payment option, you </font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;">have to click on&nbsp; </font></span><b><font style="vertical-align: inherit;">Proceed .</font></b></font><span style="font-weight: 400;"><font style="vertical-align: inherit;"></font></span><b><font style="vertical-align: inherit;"></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"></font></span><b><font style="vertical-align: inherit;"></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"></font></span></li>
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">On the next screen you will be given information about the charge for your learning license and the charge for LL TEST. You can make payment from here, for this you have to select the payment gateway. After this, you have to </font></font></span><font style="vertical-align: inherit;"><span style="font-weight: 400;"><font style="vertical-align: inherit;">enter </font></span></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">the Captcha code and </font></font></b><font style="vertical-align: inherit;"><span style="font-weight: 400;"><font style="vertical-align: inherit;">click on&nbsp; </font></span><b><font style="vertical-align: inherit;">Pay Now .</font></b></font><span style="font-weight: 400;"><font style="vertical-align: inherit;"></font></span><b><font style="vertical-align: inherit;"></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"></font></span></li>
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">On the next screen you will see bank related details, here you have to </font></font></span><font style="vertical-align: inherit;"><span style="font-weight: 400;"><font style="vertical-align: inherit;">click on </font></span></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Terms and Conditions and then </font></font></b><font style="vertical-align: inherit;"><span style="font-weight: 400;"><font style="vertical-align: inherit;">click on </font></span><b><font style="vertical-align: inherit;">Proceed Payment .</font></b></font><span style="font-weight: 400;"><font style="vertical-align: inherit;"></font></span><b><font style="vertical-align: inherit;"></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"></font></span></li>
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">After this you will reach the payment gateway and here you can make payment as per your convenience through internet banking, debit card, credit card etc.</font></font></span></li>
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Once the payment is completed, a new screen will open in front of you. Here you will get the option of </font></font></span><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Click Here to Print Receipt, </font></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">by clicking on which you can download the payment receipt by entering the Captcha Code.</font></font></span></li>
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">You have to save this receipt in PDF format on your phone. Now you do not need to go to the RTO office. In this way, you can apply for your learning license online.</font></font></span></li>
<li><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">You can check the status of your driving license online, for this you have to go to this link  Here you have to enter your Application Number and Date of Birth. After this you have to click on </font></font></span><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">SUBMIT </font></font></b><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">. In this way you can check the status of your application.</font></font></span></li>
</ul><a href="https://parivahan.gov.in/sarathiservicecov5/applViewStatus.do">click here</a>
<h2><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">conclusion&nbsp;</font></font></span></h2>
<p><span style="font-weight: 400;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">In this article, we have told you how to apply for a learning license online from home. You can apply for your learning license by following the step-by-step process given by us. If you have any question related to this article, then you can ask us through the comment box.</font></font></span></p>

</div>

</div>
</article>
  `;

  return (
    <section className="w-full mx-auto max-w-[420px]  flex flex-col rounded-2xl p-2 border-2 border-gray-700 demo">
      <div className="border-y-2 border-gray-700">
        <Ad2 />
      </div>
      <h2>क्या आप ड्राइविंग लाइसेंस बनवाना चाहते हो?</h2>
      <ExtraButton href={link} className="bg-green-700 border-yellow-500">
        Yes ✅
      </ExtraButton>
      <ExtraButton
        href={link}
        className="bg-red-700 mt-4 mb-6 border-yellow-500"
      >
        No ❌
      </ExtraButton>
      <SmallAd />
      <div dangerouslySetInnerHTML={{ __html: page }} className="demo"></div>
    </section>
  );
};

export default aPage;
