import { Ad1, Ad2, Ad3 } from "@/components/ads/ads";

const link = "/vidyadhan-scholarship-2024";

const cPage = () => {
  const page = `
 <article id="post-143626" class="single-view post-143626 post type-post status-publish format-standard has-post-thumbnail hentry category-scholarship tag-medhasoft-apply-for-bihar-scholarship tag-medhasoft-bih-nic-in-scholarship-status tag-medhasoft-bih-nic-in-scholarship" itemprop="blogPost" itemscope="" itemtype="http://schema.org/BlogPosting" style="height: auto !important;">


		<h2 class="entry-title" itemprop="headline"><a href="/">Medhasoft Apply For Bihar Scholarship 2024: Online Application For Matric, Inter And Graduation Pass Scholarship Started</a></h2>


<div class="entry-content cf" itemprop="text" style="height: auto !important;">
	
	
	

<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Medhasoft Apply For Bihar Scholarship:</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> &nbsp; Are you also&nbsp; a student of </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Bihar Board&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> who&nbsp; </font><font style="vertical-align: inherit;">wants to get&nbsp; </font><strong><font style="vertical-align: inherit;">scholarship&nbsp; </font></strong></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">ranging from ₹ 10,000 to ₹ 50,000,&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> then this article of ours is only for you, in which we will tell you </font><strong><a href="/"><font style="vertical-align: inherit;">in</font></a></strong><strong><font style="vertical-align: inherit;"> detail about Medhasoft Apply For Bihar Scholarship,&nbsp; </font></strong><strong><a href="//"><span style="color: #000000;"><font style="vertical-align: inherit;">for</font></span></a></strong><font style="vertical-align: inherit;"> which you&nbsp; </font><font style="vertical-align: inherit;">will have to read this article </font><strong><a href="/"><font style="vertical-align: inherit;">carefully .</font></a></strong></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><a href="/"><font style="vertical-align: inherit;"></font><span style="color: #000000;"><font style="vertical-align: inherit;"></font></span><font style="vertical-align: inherit;"></font></a>&nbsp;</strong><font style="vertical-align: inherit;"></font></p>


<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Here we would like to tell you that,&nbsp; </font><font style="vertical-align: inherit;">to&nbsp; </font><strong><font style="vertical-align: inherit;">apply&nbsp;</font></strong><font style="vertical-align: inherit;"> for&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Medhasoft </font><font style="vertical-align: inherit;">Application For Bihar </font><a href="/"><font style="vertical-align: inherit;">Scholarship </font></a></font><span style="color: #000000;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">,</font></font></span><font style="vertical-align: inherit;"></font><a href="/"><font style="vertical-align: inherit;"></font></a>&nbsp;</strong><font style="vertical-align: inherit;"><strong><font style="vertical-align: inherit;"> you will have to keep your current mobile number and email ID&nbsp;</font></strong><font style="vertical-align: inherit;"> ready with you so that you can easily&nbsp; </font><strong><font style="vertical-align: inherit;">apply&nbsp;</font></strong><font style="vertical-align: inherit;"> for&nbsp; this </font><strong><font style="vertical-align: inherit;">scholarship</font></strong><font style="vertical-align: inherit;"> and avail its benefits and</font></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">In the last step of the article, we will provide you&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">quick links&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> so that you can easily get similar articles and benefit from them.</font></font></p>

<p><img fetchpriority="high" decoding="async" class="alignnone size-full wp-image-143643" src="https://biharhelp.in/wp-content/uploads/2023/08/Medhasoft-Apply-For-Bihar-Scholarship-2023.jpg" alt="Medhasoft Apply For Bihar Scholarship 2023" width="1200" height="800" data-sitemapexclude="true" title="Medhasoft Apply For Bihar Scholarship" srcset="https://biharhelp.in/wp-content/uploads/2023/08/Medhasoft-Apply-For-Bihar-Scholarship-2023.jpg 1200w, https://biharhelp.in/wp-content/uploads/2023/08/Medhasoft-Apply-For-Bihar-Scholarship-2023-300x200.jpg 300w, https://biharhelp.in/wp-content/uploads/2023/08/Medhasoft-Apply-For-Bihar-Scholarship-2023-1024x683.jpg 1024w, https://biharhelp.in/wp-content/uploads/2023/08/Medhasoft-Apply-For-Bihar-Scholarship-2023-768x512.jpg 768w, https://biharhelp.in/wp-content/uploads/2023/08/Medhasoft-Apply-For-Bihar-Scholarship-2023-150x100.jpg 150w" sizes="(max-width: 1200px) 100vw, 1200px" loading="lazy"></p>



<h2 style="text-align: center;"><span class="ez-toc-section" id="%E0%A4%AE%E0%A5%88%E0%A4%9F%E0%A5%8D%E0%A4%B0%E0%A4%BF%E0%A4%95_%E0%A4%87%E0%A4%82%E0%A4%9F%E0%A4%B0_%E0%A4%B5_%E0%A4%B8%E0%A5%8D%E0%A4%A8%E0%A4%BE%E0%A4%A4%E0%A4%95_%E0%A4%AA%E0%A4%BE%E0%A4%B8_%E0%A4%B5%E0%A4%BF%E0%A4%A6%E0%A5%8D%E0%A4%AF%E0%A4%BE%E0%A4%B0%E0%A5%8D%E0%A4%A5%E0%A4%BF%E0%A4%AF%E0%A5%8B_%E0%A4%B9%E0%A5%87%E0%A4%A4%E0%A5%81_%E0%A4%B8%E0%A5%8D%E0%A4%95%E0%A5%89%E0%A4%B2%E0%A4%B0%E0%A4%B6%E0%A4%BF%E0%A4%AA%E0%A5%8D%E0%A4%B8_%E0%A4%95%E0%A5%87_%E0%A4%B2%E0%A4%BF%E0%A4%8F_%E0%A4%86%E0%A4%B5%E0%A5%87%E0%A4%A6%E0%A4%A8_%E0%A4%AA%E0%A5%8D%E0%A4%B0%E0%A4%95%E0%A5%8D%E0%A4%B0%E0%A4%BF%E0%A4%AF%E0%A4%BE_%E0%A4%B6%E0%A5%81%E0%A4%B0%E0%A5%81_%E0%A4%9C%E0%A4%BE%E0%A4%A8%E0%A5%87_%E0%A4%95%E0%A5%88%E0%A4%B8%E0%A5%87_%E0%A4%95%E0%A4%B0%E0%A4%A8%E0%A4%BE_%E0%A4%B9%E0%A5%8B%E0%A4%97%E0%A4%BE_%E0%A4%85%E0%A4%AA%E0%A5%8D%E0%A4%B2%E0%A4%BE%E0%A4%88_%E2%80%93_Medhasoft_Apply_For_Bihar_Scholarship" ez-toc-data-id="#मैट्रिक_इंटर_व_स्नातक_पास_विद्यार्थियो_हेतु_स्कॉलरशिप्स_के_लिए_आवेदन_प्रक्रिया_शुरु_जाने_कैसे_करना_होगा_अप्लाई_–_Medhasoft_Apply_For_Bihar_Scholarship"></span><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Application process for scholarships for Matriculation, Intermediate and Graduate pass students has started, know how to apply - Medhasoft </font></font><a href="/"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Apply</font></font></a><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> For Bihar Scholarship?</font></font></strong><span class="ez-toc-section-end"></span></h2>
<p><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"><strong><font style="vertical-align: inherit;">Welcoming&nbsp;</font></strong><font style="vertical-align: inherit;"> all the students&nbsp; </font><strong><font style="vertical-align: inherit;">who have passed&nbsp; </font></strong></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Matriculation, Intermediate and Bachelors </font></font><span style="color: #000000;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">from</font></font></span><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> Bihar&nbsp; </font><strong><font style="vertical-align: inherit;">Board&nbsp;</font></strong><font style="vertical-align: inherit;"> in this article &nbsp;, we will tell you in detail </font><font style="vertical-align: inherit;">about </font><strong><font style="vertical-align: inherit;">Medhasoft Apply For </font></strong><strong><a href=><font style="vertical-align: inherit;">Bihar</font></a></strong><strong><font style="vertical-align: inherit;"> Scholarship , for which you will have to read this article </font></strong><strong><font style="vertical-align: inherit;">carefully</font></strong><font style="vertical-align: inherit;"> so that you can get complete information.</font></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font><a href="/"><font style="vertical-align: inherit;"></font></a><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">At the same time, we&nbsp; </font><font style="vertical-align: inherit;">would like to tell&nbsp; all </font><strong><font style="vertical-align: inherit;">the students&nbsp;</font></strong><font style="vertical-align: inherit;"> of&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Bihar Board&nbsp; that </font></font></strong><font style="vertical-align: inherit;"><strong><font style="vertical-align: inherit;">to&nbsp; </font></strong><strong><span style="color: #000000;"><font style="vertical-align: inherit;">apply</font></span></strong><font style="vertical-align: inherit;"> for&nbsp; </font><strong><font style="vertical-align: inherit;">Medhasoft Apply For Bihar Scholarship,&nbsp;&nbsp;</font></strong><font style="vertical-align: inherit;"> you&nbsp; will have to apply by adopting </font><strong><font style="vertical-align: inherit;">the online application process&nbsp;</font></strong><font style="vertical-align: inherit;"> , in which you should not face any problem, for this we &nbsp; will tell you about the&nbsp; </font><font style="vertical-align: inherit;">entire&nbsp; </font><a href="/"><strong><font style="vertical-align: inherit;">application process&nbsp;</font></strong></a><strong><font style="vertical-align: inherit;"> so that you can easily apply&nbsp;</font></strong>< font style="vertical-align: inherit;"> for&nbsp; this </font><strong><font style="vertical-align: inherit;">scholarship&nbsp;</font></strong><font style="vertical-align: inherit;"> and get its benefits and</font></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><span style="color: #000000;"><font style="vertical-align: inherit;"></font></span><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><a href="/"><strong><font style="vertical-align: inherit;"></font></strong></a><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">In the last step of the article, we will provide you&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">quick links&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> so that you can easily get similar articles and benefit from them.</font></font></p>















<h2 style="text-align: center;"><span class="ez-toc-section" id="How_to_Apply_Online_Medhasoft_Apply_For_Bihar_Scholarship" ez-toc-data-id="#How_to_Apply_Online_Medhasoft_Apply_For_Bihar_Scholarship"></span><strong>How to Apply Online Medhasoft Apply For Bihar Scholarship?</strong><span class="ez-toc-section-end"></span></h2>
<p><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">All&nbsp; </font><strong><font style="vertical-align: inherit;">the students&nbsp; of </font></strong><strong><font style="vertical-align: inherit;">Bihar Board&nbsp;</font></strong><font style="vertical-align: inherit;"> who are willing to&nbsp; </font><strong><font style="vertical-align: inherit;">apply&nbsp;</font></strong><font style="vertical-align: inherit;"> for&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">10th pass, 12th pass and </font></font><span style="color: #000000;"><a style="color: #000000;" href="https://biharhelp.in/inter-pass-15000-scholarship-2023-apply/"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Matric</font></font></a></span><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> scholarship scheme&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> can </font><strong><font style="vertical-align: inherit;">apply&nbsp;</font></strong><font style="vertical-align: inherit;"> by&nbsp; </font><strong><font style="vertical-align: inherit;">following&nbsp;</font></strong><font style="vertical-align: inherit;"> these steps&nbsp; which are as follows –</font></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font></p>
<p><img decoding="async" class="alignnone" src="http://medhasoft.bih.nic.in/medhaint2022/(S(ok4mmec2cftqiqcbn3nqarqg))/images/flow.png" alt="Medhasoft Apply For Bihar Scholarship" width="7912" height="444" title="Medhasoft Apply For Bihar Scholarship" loading="lazy"></p>
<ul style="list-style:disc">
<li><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">To&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">apply&nbsp; </font></font></strong><font style="vertical-align: inherit;"><strong><font style="vertical-align: inherit;">for Medhasoft Apply For Bihar Scholarship,&nbsp;</font></strong><font style="vertical-align: inherit;"> first&nbsp; of all all </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">the students&nbsp; will have to come to </font></font></strong><font style="vertical-align: inherit;"><strong><font style="vertical-align: inherit;">the home page&nbsp;</font></strong><font style="vertical-align: inherit;"> of&nbsp; </font><font style="vertical-align: inherit;">its&nbsp; </font></font><strong><a href="http://medhasoft.bih.nic.in/" rel="nofollow noopener" target="_blank"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">official website</font></font></a>&nbsp;</strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> , which will be like this –</font></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font></li>
</ul>
<p><img decoding="async" class="aligncenter" src="http://medhasoft.bih.nic.in/images/a1.jpg" alt="Medhasoft Apply For Bihar Scholarship" width="438" height="84" title="Medhasoft Apply For Bihar Scholarship" loading="lazy"></p>
<ul style="list-style:disc">
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Now here you&nbsp; will find </font><strong><font style="vertical-align: inherit;">different sections&nbsp;</font></strong><font style="vertical-align: inherit;"> of&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">all </font><font style="vertical-align: inherit;">scholarship&nbsp; </font></font><span style="color: #000000;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">schemes</font></font></span><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> ,</font></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Select the </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">scholarship scheme&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> you&nbsp; are </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">eligible&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> for&nbsp; and </font><font style="vertical-align: inherit;">click on </font><font style="vertical-align: inherit;">the&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Apply&nbsp;&nbsp; </font></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">link&nbsp; .</font></font></strong><font style="vertical-align: inherit;"></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">After clicking, a new page will open in front of you where you&nbsp; will get the option of </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Students Click Here To Apply&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> , on which you have to click,</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">After clicking, the&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">guidelines&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> page will open in front of you where you&nbsp; will have to read all </font><font style="vertical-align: inherit;">the&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">guidelines </font></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">carefully&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> and&nbsp; </font><font style="vertical-align: inherit;">give&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">your approval&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> and click on </font><font style="vertical-align: inherit;">the&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">proceed&nbsp; </font></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">option&nbsp; .</font></font></strong><font style="vertical-align: inherit;"></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">After clicking, the&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">application form&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> will open in front of you which you&nbsp; will have to </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">fill carefully&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> .</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">All the required documents need to be </font><strong><span style="color: #000000;"><font style="vertical-align: inherit;">scanned</font></span></strong><font style="vertical-align: inherit;"> and </font><strong><font style="vertical-align: inherit;">uploaded.&nbsp;</font></strong></font><span style="color: #000000;">&nbsp;</span><strong><span style="color: #000000;"><font style="vertical-align: inherit;"></font></span><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Lastly, you&nbsp; have to click on </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">submit&nbsp; </font></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">option&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> after which you&nbsp; </font><font style="vertical-align: inherit;">will get&nbsp; your </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">application&nbsp; </font></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">slip&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> which you have to&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">print&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> and&nbsp; keep </font><font style="vertical-align: inherit;">it&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">safe&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> etc.</font></font></li>
</ul>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">After following all the above steps, all you&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">students&nbsp; will be able </font></font></strong><font style="vertical-align: inherit;"><strong><span style="color: #000000;"><a style="color: #000000;" href="https://biharhelp.in/inter-pass-15000-scholarship-2023-apply/"><font style="vertical-align: inherit;">to</font></a></span></strong><strong><font style="vertical-align: inherit;"> apply</font></strong><font style="vertical-align: inherit;"> for&nbsp; </font><font style="vertical-align: inherit;">all these&nbsp; </font><strong><font style="vertical-align: inherit;">scholarship schemes&nbsp;</font></strong><font style="vertical-align: inherit;"> very&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">easily&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> and avail their benefits.</font></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font><span style="color: #000000;"><a style="color: #000000;" href="https://biharhelp.in/inter-pass-15000-scholarship-2023-apply/"><font style="vertical-align: inherit;"></font></a></span>&nbsp;</strong><font style="vertical-align: inherit;"></font></p>
<h2><span class="ez-toc-section" id="%E0%A4%89%E0%A4%AA%E0%A4%B8%E0%A4%82%E0%A4%B9%E0%A4%BE%E0%A4%B0" ez-toc-data-id="#उपसंहार"></span><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Epilogue</font></font></strong><span class="ez-toc-section-end"></span></h2>
<p><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">In this article, we have not only told all our </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">brilliant students&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> of&nbsp; </font><strong><font style="vertical-align: inherit;">Bihar Board&nbsp;</font></strong><font style="vertical-align: inherit;"> about&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Medhasoft Apply For Bihar School </font><font style="vertical-align: inherit;">Scholarship </font></font><span style="color: #000000;"><a style="color: #000000;" href="https://biharhelp.in/inter-pass-15000-scholarship-2023-apply/"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">in</font></font></a></span><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> detail, but we have also told you about the&nbsp; entire </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">online application process&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> so that you can&nbsp; easily </font><strong><font style="vertical-align: inherit;">apply&nbsp;</font></strong><font style="vertical-align: inherit;"> for&nbsp; all these </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">scholarships&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> and ensure your </font><strong><font style="vertical-align: inherit;">academic development&nbsp;</font></strong><font style="vertical-align: inherit;"> by getting&nbsp; </font><strong><font style="vertical-align: inherit;">the desired scholarship&nbsp; .</font></strong></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Thus, at the end of the article, we hope that you liked our article very much, for which you&nbsp; </font><font style="vertical-align: inherit;">will </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">like, share and comment&nbsp; on our article.</font></font></strong><font style="vertical-align: inherit;"></font></p>

	</div>


</article>
  `;

  return (
    <section className="w-full mx-auto max-w-[420px] flex flex-col rounded-2xl p-2 border-2 border-gray-700 demo">
      <div className="border-y-2 border-gray-700">
        <Ad3 />
      </div>
      <div className="w-full my-4 flex items-center justify-center">
        <iframe
          id="twitter-widget-0"
          allowTransparency={true}
          allowFullScreen={true}
          title="X Post"
          style={{
            position: "static",
            visibility: "visible",
            width: "320px",
            height: "298px",
            display: "block",
          }}
          src="https://platform.twitter.com/embed/Tweet.html?dnt=false&amp;embedId=twitter-widget-0&amp;features=eyJ0ZndfdGltZWxpbmVfbGlzdCI6eyJidWNrZXQiOltdLCJ2ZXJzaW9uIjpudWxsfSwidGZ3X2ZvbGxvd2VyX2NvdW50X3N1bnNldCI6eyJidWNrZXQiOnRydWUsInZlcnNpb24iOm51bGx9LCJ0ZndfdHdlZXRfZWRpdF9iYWNrZW5kIjp7ImJ1Y2tldCI6Im9uIiwidmVyc2lvbiI6bnVsbH0sInRmd19yZWZzcmNfc2Vzc2lvbiI6eyJidWNrZXQiOiJvbiIsInZlcnNpb24iOm51bGx9LCJ0ZndfZm9zbnJfc29mdF9pbnRlcnZlbnRpb25zX2VuYWJsZWQiOnsiYnVja2V0Ijoib24iLCJ2ZXJzaW9uIjpudWxsfSwidGZ3X21peGVkX21lZGlhXzE1ODk3Ijp7ImJ1Y2tldCI6InRyZWF0bWVudCIsInZlcnNpb24iOm51bGx9LCJ0ZndfZXhwZXJpbWVudHNfY29va2llX2V4cGlyYXRpb24iOnsiYnVja2V0IjoxMjA5NjAwLCJ2ZXJzaW9uIjpudWxsfSwidGZ3X3Nob3dfYmlyZHdhdGNoX3Bpdm90c19lbmFibGVkIjp7ImJ1Y2tldCI6Im9uIiwidmVyc2lvbiI6bnVsbH0sInRmd19kdXBsaWNhdGVfc2NyaWJlc190b19zZXR0aW5ncyI6eyJidWNrZXQiOiJvbiIsInZlcnNpb24iOm51bGx9LCJ0ZndfdXNlX3Byb2ZpbGVfaW1hZ2Vfc2hhcGVfZW5hYmxlZCI6eyJidWNrZXQiOiJvbiIsInZlcnNpb24iOm51bGx9LCJ0ZndfdmlkZW9faGxzX2R5bmFtaWNfbWFuaWZlc3RzXzE1MDgyIjp7ImJ1Y2tldCI6InRydWVfYml0cmF0ZSIsInZlcnNpb24iOm51bGx9LCJ0ZndfbGVnYWN5X3RpbWVsaW5lX3N1bnNldCI6eyJidWNrZXQiOnRydWUsInZlcnNpb24iOm51bGx9LCJ0ZndfdHdlZXRfZWRpdF9mcm9udGVuZCI6eyJidWNrZXQiOiJvbiIsInZlcnNpb24iOm51bGx9fQ%3D%3D&amp;frame=false&amp;hideCard=false&amp;hideThread=false&amp;id=1743620721018826896&amp;lang=en&amp;maxWidth=560px&amp;origin=https%3A%2F%2Fbuzzlenews.com%2Fc.html&amp;sessionId=355e154fe49335923557d26b8a2bbd9f883e149b&amp;theme=light&amp;widgetsVersion=2615f7e52b7e0%3A1702314776716&amp;width=550px"
          data-tweet-id="1743620721018826896"
        ></iframe>
      </div>
      <div className="border-y-2 border-gray-700">
        <Ad2 />
      </div>

      <div dangerouslySetInnerHTML={{ __html: page }} className="demo"></div>
    </section>
  );
};

export default cPage;
