import { Ad1, Ad3, SmallAd2 } from "@/components/ads/ads";
import ExtraButton from "@/components/etc/button-extra";

const link = "/mukhyamantri-kanya-utthan-yojana-graduation";

const aPage = () => {
  const page = `
  <article id="post-203853" class="single-view post-203853 post type-post status-publish format-standard has-post-thumbnail hentry category-scholarship" itemprop="blogPost" itemscope="" itemtype="http://schema.org/BlogPosting" style="height: auto !important;">
  <h2>Vidyadhan Scholarship 2024 – Online Apply, Login, Date, Documents, Eligibility & Qualification<h2>
<h3 style="text-align: center;"><span class="ez-toc-section" id="%E0%A4%B8%E0%A4%BE%E0%A4%B2_2024_%E0%A4%AE%E0%A5%87_%E0%A4%AE%E0%A5%88%E0%A4%9F%E0%A5%8D%E0%A4%B0%E0%A4%BF%E0%A4%95_%E0%A4%AA%E0%A4%BE%E0%A4%B8_%E0%A4%B8%E0%A5%8D%E0%A4%9F%E0%A5%82%E0%A4%A1%E0%A5%87%E0%A4%82%E0%A4%9F%E0%A5%8D%E0%A4%B8_%E0%A4%95%E0%A5%8B_%E0%A4%B8%E0%A4%B0%E0%A4%95%E0%A4%BE%E0%A4%B0_%E0%A4%A6%E0%A5%87_%E0%A4%B0%E0%A4%B9%E0%A5%80_%E0%A4%B9%E0%A5%88_%E0%A4%AA%E0%A5%82%E0%A4%B0%E0%A5%87_%E2%82%B9_10000_%E0%A4%95%E0%A5%80_%E0%A4%B8%E0%A5%8D%E0%A4%95%E0%A5%89%E0%A4%B2%E0%A4%B0%E0%A4%B6%E0%A4%BF%E0%A4%AA_%E0%A4%9C%E0%A4%BE%E0%A4%A8%E0%A5%87_%E0%A4%95%E0%A5%8D%E0%A4%AF%E0%A4%BE_%E0%A4%B9%E0%A5%88_%E0%A4%B8%E0%A5%8D%E0%A4%95%E0%A5%80%E0%A4%AE_%E0%A4%94%E0%A4%B0_%E0%A4%95%E0%A5%8D%E0%A4%AF%E0%A4%BE_%E0%A4%B9%E0%A5%88_%E0%A4%AA%E0%A5%82%E0%A4%B0%E0%A5%80_%E0%A4%86%E0%A4%B5%E0%A5%87%E0%A4%A6%E0%A4%A8_%E0%A4%AA%E0%A5%8D%E0%A4%B0%E0%A4%95%E0%A5%8D%E0%A4%B0%E0%A4%BF%E0%A4%AF%E0%A4%BE_%E2%80%93_Vidyadhan_Scholarship_2024" ez-toc-data-id="#साल_2024_मे_मैट्रिक_पास_स्टूडेंट्स_को_सरकार_दे_रही_है_पूरे_₹_10000_की_स्कॉलरशिप_जाने_क्या_है_स्कीम_और_क्या_है_पूरी_आवेदन_प्रक्रिया_–_Vidyadhan_Scholarship_2024"></span><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">In the year 2024, the government is giving a scholarship of full ₹ 10,000 to matriculation pass students, know what is the scheme and what is the complete application process – Vidyadhan Scholarship 2024?</font></font></strong><span class="ez-toc-section-end"></span></h3>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">In this article, we&nbsp; </font><font style="vertical-align: inherit;">want to&nbsp; </font><strong><font style="vertical-align: inherit;">heartily welcome&nbsp; all of you </font></strong><strong><font style="vertical-align: inherit;">10th pass students&nbsp;</font></strong><font style="vertical-align: inherit;"> of&nbsp; </font><font style="vertical-align: inherit;">Bihar&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Board&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> who want to get </font><strong><font style="vertical-align: inherit;">scholarship&nbsp;</font></strong><font style="vertical-align: inherit;"> for&nbsp; </font><strong><font style="vertical-align: inherit;">studying&nbsp; </font></strong><strong><font style="vertical-align: inherit;">Inter and Degree Course&nbsp;</font></strong><font style="vertical-align: inherit;"> and&nbsp; that is why we will tell you in detail about </font><strong><font style="vertical-align: inherit;">Vidyadhan Scholarship 2024</font></strong><font style="vertical-align: inherit;"> in this article , to get complete detailed information about which you have to stay with us.</font></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><strong>&nbsp;&nbsp;</strong><font style="vertical-align: inherit;"></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">At the same time, let us tell you that, to </font><strong><font style="vertical-align: inherit;">apply&nbsp; for </font></strong></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Vidyadhan Scholarship 2024</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> ,&nbsp; </font><font style="vertical-align: inherit;">all the students&nbsp; </font><font style="vertical-align: inherit;">will have to&nbsp; </font><strong><font style="vertical-align: inherit;">apply&nbsp;</font></strong><font style="vertical-align: inherit;"> by adopting&nbsp; </font><strong><font style="vertical-align: inherit;">the online application process&nbsp;</font></strong><font style="vertical-align: inherit;"> , in which you do not have any problem, for this we will tell you about the&nbsp; entire </font><strong><font style="vertical-align: inherit;">application process&nbsp; , for which you have to </font></strong><strong><font style="vertical-align: inherit;">read&nbsp; </font></strong><strong><font style="vertical-align: inherit;">this article&nbsp;</font></strong><font style="vertical-align: inherit;"> carefully&nbsp; </font><font style="vertical-align: inherit;">and</font></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">In the last step of the article, we will provide you&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">quick links&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> so that you can easily get similar articles and benefit from them.</font></font></p>
<h2 style="text-align: center;"><span class="ez-toc-section" id="Vidyadhan_Scholarship_2024_%E2%80%93_%E0%A4%86%E0%A4%95%E0%A4%B0%E0%A5%8D%E0%A4%B7%E0%A4%95_%E0%A4%B2%E0%A4%BE%E0%A4%AD_%E0%A4%8F%E0%A4%82%E0%A4%B5_%E0%A4%AB%E0%A4%BE%E0%A4%AF%E0%A4%A6%E0%A5%87%E0%A4%82_%E0%A4%95%E0%A5%8D%E0%A4%AF%E0%A4%BE_%E0%A4%B9%E0%A5%88" ez-toc-data-id="#Vidyadhan_Scholarship_2024_–_आकर्षक_लाभ_एंव_फायदें_क्या_है"></span><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Vidyadhan Scholarship 2024 – What are the attractive benefits and advantages?</font></font></strong><span class="ez-toc-section-end"></span></h2>
<p><font style="vertical-align: inherit;"><strong><font style="vertical-align: inherit;">The benefits and advantages&nbsp;</font></strong><font style="vertical-align: inherit;"> received under&nbsp; </font><font style="vertical-align: inherit;">this&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">scholarship scheme&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> are as follows –</font></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font></p>
<ul style="list-style: disc;">
<li><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">All you&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">10th pass students&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> of </font><strong><font style="vertical-align: inherit;">Bihar state</font></strong><font style="vertical-align: inherit;"> will be given the benefit of </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Vidyadhan Scholarship 2024 ,</font></font></strong><strong>&nbsp;</strong><font style="vertical-align: inherit;"></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Let us tell you that,&nbsp; </font><strong><font style="vertical-align: inherit;">150 10th pass </font></strong><strong><span style="color: #000000;"><font style="vertical-align: inherit;">students </font></span></strong><strong><span style="color: #000000;"><a style="color: #000000;" href="https://biharhelp.in/epfo-pension-scheme/"><font style="vertical-align: inherit;">of</font></a></span></strong><font style="vertical-align: inherit;"> Bihar </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Board&nbsp; </font></font></strong><font style="vertical-align: inherit;"><span style="color: #000000;"><font style="vertical-align: inherit;">will&nbsp;</font></span><font style="vertical-align: inherit;"> be given </font><strong><font style="vertical-align: inherit;">scholarship&nbsp; ,</font></strong></font><strong><font style="vertical-align: inherit;"></font><span style="color: #000000;"><font style="vertical-align: inherit;"></font><a style="color: #000000;" href="https://biharhelp.in/epfo-pension-scheme/"><font style="vertical-align: inherit;"></font></a>&nbsp;</span></strong><span style="color: #000000;"><font style="vertical-align: inherit;"></font></span><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font></li>
<li><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">You will be given a </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">total </font></font><span style="color: #000000;"><font style="vertical-align: inherit;"></font></span><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">scholarship&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> of&nbsp; </font><strong><span style="color: #000000;"><font style="vertical-align: inherit;">₹</font></span></strong><strong><font style="vertical-align: inherit;"> 10,000&nbsp;</font></strong><font style="vertical-align: inherit;"> for&nbsp; </font><strong><font style="vertical-align: inherit;">intermediate&nbsp; studies,</font></strong></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">If you&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">perform well&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> , you&nbsp; </font><font style="vertical-align: inherit;">will be awarded </font><strong><font style="vertical-align: inherit;">a scholarship&nbsp;</font></strong><font style="vertical-align: inherit;"> of&nbsp; </font><strong><font style="vertical-align: inherit;">₹ 15,000 to ₹ 60,000</font></strong><font style="vertical-align: inherit;"> for&nbsp; </font><strong><font style="vertical-align: inherit;">pursuing&nbsp; </font></strong></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">a degree course&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> .&nbsp;</font></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">In the end, your&nbsp; </font><strong><font style="vertical-align: inherit;">bright future&nbsp;</font></strong><font style="vertical-align: inherit;"> will&nbsp; be </font><strong><font style="vertical-align: inherit;">created&nbsp; by </font></strong><strong><font style="vertical-align: inherit;">educational empowerment&nbsp;</font></strong><font style="vertical-align: inherit;"> of&nbsp; </font><font style="vertical-align: inherit;">all you&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Bihar </font></font><span style="color: #000000;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Board</font></font></span><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> students&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> etc.</font></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font></li>
</ul>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">With the help of all the above points, we&nbsp; </font><font style="vertical-align: inherit;">have told you about&nbsp; </font><strong><font style="vertical-align: inherit;">the benefits&nbsp;</font></strong><font style="vertical-align: inherit;"> of&nbsp; this </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">scholarship scheme&nbsp; so that you can easily </font></font></strong><font style="vertical-align: inherit;"><strong><font style="vertical-align: inherit;">apply</font></strong><font style="vertical-align: inherit;"> for&nbsp; this </font><strong><font style="vertical-align: inherit;">scholarship&nbsp;</font></strong><font style="vertical-align: inherit;"> and avail its benefits.</font></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font></p>
<h2 style="text-align: center;"><span class="ez-toc-section" id="_Required_Documents_For_Vidyadhan_Scholarship_2024_Apply_Online" ez-toc-data-id="#_Required_Documents_For_Vidyadhan_Scholarship_2024_Apply_Online"></span>&nbsp;<strong>Required Documents For Vidyadhan Scholarship 2024 Apply Online?</strong><span class="ez-toc-section-end"></span></h2>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">On the other hand, all of you&nbsp; </font><font style="vertical-align: inherit;">students&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">will&nbsp; have to </font></font></strong><font style="vertical-align: inherit;"><strong><font style="vertical-align: inherit;">submit&nbsp; </font></strong></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">some documents&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> which&nbsp; </font><font style="vertical-align: inherit;">are as follows </font></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font></p>
<ul style="list-style: disc;">
<li><font style="vertical-align: inherit;"><strong><font style="vertical-align: inherit;">Aadhar card</font></strong><font style="vertical-align: inherit;"> of the applicant student&nbsp; ,</font></font><strong><font style="vertical-align: inherit;"></font></strong></li>
<li><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Income </font></font><span style="color: #000000;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Certificate</font></font></span><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> ,</font></font></strong></li>
<li><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Address proof,</font></font></strong></li>
<li><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">caste certificate,</font></font></strong></li>
<li><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">10th class passing certificate </font></font><span style="color: #000000;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">and</font></font></span><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> mark sheet,</font></font></strong></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Active mobile number and</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Passport size photograph etc.</font></font></li>
</ul>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">By completing all the above documents, you can easily </font><strong><font style="vertical-align: inherit;">apply</font></strong><font style="vertical-align: inherit;"> for this </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">scholarship</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> and avail its benefits.</font></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font></p>
<h2 style="text-align: center;"><span class="ez-toc-section" id="Required_Qualification_For_Vidyadhan_Scholarship_2024_Registration" ez-toc-data-id="#Required_Qualification_For_Vidyadhan_Scholarship_2024_Registration"></span><strong>Required Qualification For Vidyadhan Scholarship 2024 Registration?</strong><span class="ez-toc-section-end"></span></h2>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">All of you&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Bihar Board&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> Matric&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">pass students</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> who </font><font style="vertical-align: inherit;">want to&nbsp; </font><strong><font style="vertical-align: inherit;">apply&nbsp;</font></strong><font style="vertical-align: inherit;"> for&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Vidyaghan Scholarship&nbsp; will have to fulfill some </font></font></strong><font style="vertical-align: inherit;"><strong><font style="vertical-align: inherit;">eligibility criteria&nbsp;</font></strong><font style="vertical-align: inherit;"> which are as follows –</font></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font></p>
<ul style="list-style: disc;">
<li><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">To apply for&nbsp; </font><strong><font style="vertical-align: inherit;">Vidyadhan Scholarship 2024</font></strong><font style="vertical-align: inherit;"> , all the students must be </font><strong><font style="vertical-align: inherit;">native residents&nbsp;</font></strong><font style="vertical-align: inherit;"> of&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Bihar </font></font><span style="color: #000000;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">state ,</font></font></span>&nbsp;</strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">The applicant&nbsp; </font><font style="vertical-align: inherit;">must have secured </font><strong><font style="vertical-align: inherit;">at least 7.5 </font></strong><strong><span style="color: #000000;"><font style="vertical-align: inherit;">CGPA</font></span></strong><strong><font style="vertical-align: inherit;"> in&nbsp;</font></strong><font style="vertical-align: inherit;"> the&nbsp; </font><strong><font style="vertical-align: inherit;">10th&nbsp;</font></strong><font style="vertical-align: inherit;"> class&nbsp; </font><strong><font style="vertical-align: inherit;">examination&nbsp; </font></strong></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">.</font></font></strong><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font><span style="color: #000000;"><font style="vertical-align: inherit;"></font></span><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">If the student&nbsp; </font><font style="vertical-align: inherit;">is&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">physically&nbsp; </font></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">handicapped&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> then he/she&nbsp; </font><font style="vertical-align: inherit;">must have obtained </font><strong><font style="vertical-align: inherit;">at least 6.5 CGPA&nbsp;</font></strong><font style="vertical-align: inherit;"> in&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">10th class&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> examination&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">etc.&nbsp;</font></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font></li>
</ul>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">By fulfilling all the above eligibility criteria, you can easily&nbsp; </font><strong><font style="vertical-align: inherit;">apply&nbsp;</font></strong><font style="vertical-align: inherit;"> for&nbsp; this </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Vidyaghan scholarship&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> and avail its benefits.</font></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font></p>
<h2 style="text-align: center;"><span class="ez-toc-section" id="How_to_Apply_Online_In_Vidyadhan_Scholarship_2024_Apply_Online" ez-toc-data-id="#How_to_Apply_Online_In_Vidyadhan_Scholarship_2024_Apply_Online"></span><strong>How to Apply Online In Vidyadhan Scholarship 2024 Apply Online?</strong><span class="ez-toc-section-end"></span></h2>
<p><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">All our&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Matric pass students&nbsp; of </font></font></strong><font style="vertical-align: inherit;"><strong><font style="vertical-align: inherit;">Bihar Board&nbsp;</font></strong><font style="vertical-align: inherit;"> who&nbsp; </font><font style="vertical-align: inherit;">want to&nbsp; </font><strong><font style="vertical-align: inherit;">apply&nbsp; </font></strong><strong><font style="vertical-align: inherit;">for&nbsp;</font></strong><font style="vertical-align: inherit;"> this&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">scholarship </font></font><span style="color: #000000;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">will</font></font></span><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"><strong><font style="vertical-align: inherit;"> have to apply&nbsp;</font></strong><font style="vertical-align: inherit;"> by&nbsp; </font><strong><font style="vertical-align: inherit;">following&nbsp;</font></strong><font style="vertical-align: inherit;"> these steps which are as follows –</font></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font></p>
<h3><span class="ez-toc-section" id="%E0%A4%B8%E0%A5%8D%E0%A4%9F%E0%A5%87%E0%A4%AA_1_%E2%80%93_%E0%A4%A8%E0%A5%8D%E0%A4%AF%E0%A5%82_%E0%A4%B0%E0%A4%9C%E0%A4%BF%E0%A4%B8%E0%A5%8D%E0%A4%9F%E0%A5%8D%E0%A4%B0%E0%A5%88%E0%A4%B6%E0%A4%A8_%E0%A4%95%E0%A4%B0%E0%A5%87%E0%A4%82" ez-toc-data-id="#स्टेप_1_–_न्यू_रजिस्ट्रैशन_करें"></span><span style="color: #800000;"><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Step 1 – Make a new registration</font></font></strong></span><span class="ez-toc-section-end"></span></h3>

<ul style="list-style: disc;">
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">After coming to the home page, you will get the option of </font><strong><a id="student-register" class="btn btn-primary" href="https://www.vidyadhan.org/register/student" rel="nofollow noopener" target="_blank"><font style="vertical-align: inherit;">Apply Now</font></a></strong><font style="vertical-align: inherit;"> on which you have to click,</font></font><strong> &nbsp;<a id="student-register" class="btn btn-primary" href="https://www.vidyadhan.org/register/student" rel="nofollow noopener" target="_blank"><font style="vertical-align: inherit;"></font></a>&nbsp;</strong><font style="vertical-align: inherit;"></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">After clicking, a new page will open in front of you which will be like this –</font></font></li>
</ul>
<p style="text-align: center;"><a href="https://biharhelp.in/wp-content/uploads/2023/07/4641-min.png"><img decoding="async" class="alignnone wp-image-140782" src="https://biharhelp.in/wp-content/uploads/2023/07/4641-min.png" alt="Vidyadhan Scholarship 2024" width="595" height="451" title="Vidyadhan Scholarship 2024" srcset="https://biharhelp.in/wp-content/uploads/2023/07/4641-min.png 794w, https://biharhelp.in/wp-content/uploads/2023/07/4641-min-300x227.png 300w, https://biharhelp.in/wp-content/uploads/2023/07/4641-min-768x581.png 768w, https://biharhelp.in/wp-content/uploads/2023/07/4641-min-150x114.png 150w" sizes="(max-width: 595px) 100vw, 595px" loading="lazy"></a></p>
<ul style="list-style: disc;">
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Now here you&nbsp; </font><font style="vertical-align: inherit;">have to enter&nbsp; your </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Gmail ID and Password&nbsp; and </font></font></strong><font style="vertical-align: inherit;"><strong><font style="vertical-align: inherit;">click&nbsp;</font></strong><font style="vertical-align: inherit;"> on&nbsp; </font><font style="vertical-align: inherit;">the&nbsp; </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">submit&nbsp; </font></font></strong><font style="vertical-align: inherit;"></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">option&nbsp;</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> .</font></font><strong><font style="vertical-align: inherit;"></font></strong><font style="vertical-align: inherit;"></font></li>
<li>क्लिक करने के बाद आपके&nbsp;<strong>जी मेल अकाउंट&nbsp;</strong> पर&nbsp;<strong> Activation Link&nbsp;</strong> भेजा जायेगा जिस पर आपको क्लिक करना&nbsp; होगा,</li>
<li>क्लिक करने के बाद आपके सामने इसका&nbsp;<strong> Student Registration From&nbsp;</strong> खुल जायेगा जिसे आपको<strong> ध्यानपूर्वक </strong> भरना होगा औऱ</li>
<li>अन्त में, आपको <strong>सबमिट </strong> के <strong>ऑ<span style="color: #000000;">प्श</span>न </strong>पर क्लिक करना होगा जिसके&nbsp; बाद आपको आपका <strong> Login ID and Password </strong> मिल जायेगा जिसे आपको <strong>सुरक्षित </strong>रखना होगा।</li>
</ul>
<h3><span class="ez-toc-section" id="%E0%A4%B8%E0%A5%8D%E0%A4%9F%E0%A5%87%E0%A4%AA_2_%E2%80%93_%E0%A4%AA%E0%A5%8B%E0%A4%B0%E0%A5%8D%E0%A4%9F%E0%A4%B2_%E0%A4%AE%E0%A5%87%E0%A4%82_%E0%A4%B2%E0%A5%89%E0%A4%97%E0%A4%BF%E0%A4%A8_%E0%A4%95%E0%A4%B0%E0%A4%95%E0%A5%87_%E0%A4%94%E0%A4%B0_Vidyadhan_Scholarship_2024_%E0%A4%B9%E0%A5%87%E0%A4%A4%E0%A5%81_%E0%A4%85%E0%A4%AA%E0%A5%8D%E0%A4%B2%E0%A4%BE%E0%A4%88_%E0%A4%95%E0%A4%B0%E0%A5%87%E0%A4%82" ez-toc-data-id="#स्टेप_2_–_पोर्टल_में_लॉगिन_करके_और_Vidyadhan_Scholarship_2024_हेतु_अप्लाई_करें"></span><span style="color: #ff6600;"><strong>स्टेप 2 – पोर्टल में लॉगिन करके और Vidyadhan Scholarship 2024 हेतु अप्लाई करें</strong></span><span class="ez-toc-section-end"></span></h3>
<ul style="list-style: disc;">
<li>पोर्टल पर सफलतापूर्वक पंजीकऱण करने के बाद आपको <strong>पोर्टल में लॉगिन&nbsp;</strong>करना होगा,</li>
<li>पोर्टल में&nbsp;<strong>लॉगिन&nbsp;</strong>करने के बाद आपके सामने इसका&nbsp;<strong>डैशबोर्ड&nbsp;</strong> खुल जायेगा जो कि, इस प्रकार का होगा –</li>
</ul>
<p style="text-align: center;"><a href="https://biharhelp.in/wp-content/uploads/2023/07/4642-min.png"><img loading="lazy" decoding="async" class="alignnone wp-image-140785" src="https://biharhelp.in/wp-content/uploads/2023/07/4642-min.png" alt="Vidyadhan Scholarship 2024" width="614" height="362" title="Vidyadhan Scholarship 2024" srcset="https://biharhelp.in/wp-content/uploads/2023/07/4642-min.png 678w, https://biharhelp.in/wp-content/uploads/2023/07/4642-min-300x177.png 300w, https://biharhelp.in/wp-content/uploads/2023/07/4642-min-150x88.png 150w" sizes="(max-width: 614px) 100vw, 614px"></a></p>
<ul style="list-style: disc;">
<li>अब यहां पर आपको <strong>Bihar plus-2 (1st year) Program 2024 ( हिंदी भाषा के लिए यहां क्लिक करें</strong> )<strong>&nbsp;</strong>के आगे ही आपको&nbsp;<strong>Apply Now&nbsp;</strong> का विकल्प मिलेगा जिस पर आपको क्लिक करना होगा,</li>
<li>क्लिक करने के बाद आपके सामने इसका&nbsp;<strong>Application Form&nbsp;</strong> खुल जायेगा जो कि, इस प्रकार का होगा –</li>
</ul>
<p style="text-align: center;"><a href="https://biharhelp.in/wp-content/uploads/2023/07/4643-min.png"><img loading="lazy" decoding="async" class="alignnone wp-image-140783" src="https://biharhelp.in/wp-content/uploads/2023/07/4643-min.png" alt="Vidyadhan Scholarship 2024" width="568" height="316" title="Vidyadhan Scholarship 2024" srcset="https://biharhelp.in/wp-content/uploads/2023/07/4643-min.png 708w, https://biharhelp.in/wp-content/uploads/2023/07/4643-min-300x167.png 300w, https://biharhelp.in/wp-content/uploads/2023/07/4643-min-150x84.png 150w" sizes="(max-width: 568px) 100vw, 568px"></a></p>
<ul style="list-style: disc;">
<li>अब आपको इस&nbsp;<strong> एप्लीकेशन फॉर्म&nbsp;</strong>को&nbsp;<strong> ध्या<span style="color: #000000;">न</span>पूर्वक भरना&nbsp;</strong>होगा,</li>
<li>इसके बाद आपको&nbsp;<strong> मांगे जाने वाले सभी दस्तावेजो&nbsp;</strong> को&nbsp;<strong>स्कैन करके अपलोड&nbsp;</strong> करना होगा और और&nbsp;<strong>सबमिट </strong>के <strong>ऑप्शन&nbsp;</strong>पर क्लिक करना होगा,</li>
<li>क्लिक करने के बाद आपके&nbsp; सामने इसकी&nbsp;<strong>रसीद&nbsp;</strong> मिल जायेगी जो कि, इस प्रकार की होगी –</li>
</ul>
<p><a href="https://biharhelp.in/wp-content/uploads/2023/07/4644-min.png"><img loading="lazy" decoding="async" class="aligncenter wp-image-140784" src="https://biharhelp.in/wp-content/uploads/2023/07/4644-min.png" alt="Vidyadhan Scholarship 2024" width="629" height="270" title="Vidyadhan Scholarship 2024" srcset="https://biharhelp.in/wp-content/uploads/2023/07/4644-min.png 807w, https://biharhelp.in/wp-content/uploads/2023/07/4644-min-300x129.png 300w, https://biharhelp.in/wp-content/uploads/2023/07/4644-min-768x330.png 768w, https://biharhelp.in/wp-content/uploads/2023/07/4644-min-150x64.png 150w" sizes="(max-width: 629px) 100vw, 629px"></a></p>
<ul style="list-style: disc;">
<li>अन्त, अब आपको इस&nbsp;<strong>रसीद&nbsp;</strong> को&nbsp;<strong>डाउ<span style="color: #000000;">नलोड</span>&nbsp;</strong> करके&nbsp;<strong>प्रिंट&nbsp;</strong> कर लेना होगा और&nbsp;<strong>सुरक्षित&nbsp;</strong> रखना होगा आदि।</li>
</ul>
<p>उपरोक्त सभी स्टेप्स को&nbsp;<strong> फॉलो&nbsp;</strong>करके&nbsp; आप आसानी से इस<strong> स्कॉलरशिप&nbsp;</strong> हेतु&nbsp;<strong> अप्लाई&nbsp;</strong> कर सकते है और इसका लाभ प्राप्त कर सकते है।</p>
<h2><span class="ez-toc-section" id="%E0%A4%B8%E0%A4%BE%E0%A4%B0%E0%A4%BE%E0%A4%82%E0%A4%B6" ez-toc-data-id="#सारांश"></span><strong>सारांश</strong><span class="ez-toc-section-end"></span></h2>
<p><strong>बिहार राज्य&nbsp;</strong>के अपने सभी&nbsp;<strong>10वीं कक्षा पास विद्यार्थियो&nbsp;</strong>को समर्पिथ इस आर्टिकल में हमने आपको विस्तार से ना केवल <strong>Vidyadhan Scholarship 2024</strong><strong>&nbsp;</strong>के बारे&nbsp; मे बताया&nbsp; बल्कि हमने आपको विस्तार से&nbsp;<strong>पूरी ऑनलाइन आवेदन प्रक्रिया&nbsp;</strong> के बारे में बताया ताकि आप आसानी से <span style="color: #000000;">इस&nbsp;<a style="color: #000000;" href="https://biharhelp.in/bihar-land-registry-update-new/"><strong> स्कॉलरशिप </strong></a> हेतु</span> <strong> अ<span style="color: #000000;">प्ला</span>ई&nbsp;</strong> कर सके और इसका लाभ प्राप्त करके अपना&nbsp;<strong> शैक्षणिक विकास&nbsp;</strong> सुनिश्चित कर सकें तथा</p>
<p>लेख के अन्त में हमें, उम्मीद है कि, आपको हमारा यह आर्टिकल बेहद पसंद आया होगा जिसके लिए आप हमारे इस आर्टिकल को&nbsp;<strong> लाईक, शेयर व कमेंट&nbsp;</strong>करेगे।</p>
</article>
  `;

  return (
    <section className="w-full mx-auto max-w-[420px]  flex flex-col rounded-2xl p-2 border-2 border-gray-700 demo">
      <div className="border-y-2 border-gray-700">
        <Ad3 />
      </div>
      <h2>क्या आपकी उम्र 13 साल से ज्यादा है ?</h2>
      <ExtraButton href={link} className="bg-green-700 border-yellow-500">
        Yes ✅
      </ExtraButton>
      <ExtraButton
        href={link}
        className="bg-red-700 mt-4 mb-6 border-yellow-500"
      >
        No ❌
      </ExtraButton>
      <SmallAd2 />
      <div dangerouslySetInnerHTML={{ __html: page }} className="demo"></div>
    </section>
  );
};

export default aPage;
